export const COLORS = {
  OPERATION: '#ff5794',
  DIRECTIVE: '#ffa500',
  OBJECT: '#70bcff',
} as const;

export const UPDATE_TYPES = {
  OPERATION_DEFINITION: 'OPERATION_DEFINITION',
  FIELD: 'FIELD',
  OBJECT: 'OBJECT',
  ARGUMENT: 'ARGUMENT',
  ARGUMENT_VARIABLE: 'ARGUMENT_VARIABLE',
  DIRECTIVE: 'DIRECTIVE',
  DIRECTIVE_VARIABLE: 'DIRECTIVE_VARIABLE',
} as const;
